### ISSUE TITLE
inception_cov instead of covariance in PLNnetwork_param? 

### ISSUE THREAD

**Issue by rwelling520** [cole-trapnell-lab/hooke#33]
Ran into an error when running new_cell_count_model: 

Error in PLNmodels::PLNnetwork_param(backend = backend, trace = ifelse(verbose,  : 
  unused argument (covariance = covariance_type)

I looked up the source code for new_cell_count_model and checked the allowed inputs for PLNnetwork_param and noticed that that function takes an inception_cov instead of covariance input. Maybe I'm using a different version or something?

https://github.com/cole-trapnell-lab/hooke/blob/2f6ca921fb0e19c9e08a45ec22628d4f57bbbf05/R/cell_count_model.R#L660C77-L660C104

**Comment by rfriedman22** [comment]
You're correct about the error here. `PLNnetwork_param` has been updated and no longer takes the `covariance` argument. We have made this change on the develop branch but not on main. I tried to make a quick patch on the main branch, but I don't have permissions on that branch. I'm waiting for them now. You could try to install the develop branch of Hooke instead, which will work, but there might be other things that are different compared to what you're used to using.

**Comment by rwelling520** [comment]
Thanks @rfriedman22 :)
